server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ffs;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show-sql: true #System.out.-
        format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        ## 아래 옵션 왠만하면 키는게 좋음
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug  #log
    org.hibernate.type: trace

